#[cfg(feature = "policy-arc")]
pub mod arc;
#[cfg(feature = "policy-card")]
pub mod car;
#[cfg(feature = "policy-clock")]
pub mod clock;
#[cfg(feature = "policy-clock-pro")]
pub mod clock_pro;
#[cfg(feature = "policy-fast-lru")]
pub mod fast_lru;
#[cfg(feature = "policy-fifo")]
pub mod fifo;
#[cfg(feature = "policy-heap-lfu")]
pub mod heap_lfu;
#[cfg(feature = "policy-lfu")]
pub mod lfu;
#[cfg(feature = "policy-lifo")]
pub mod lifo;
#[cfg(feature = "policy-lru")]
pub mod lru;
#[cfg(feature = "policy-lru-k")]
pub mod lru_k;
#[cfg(feature = "policy-mfu")]
pub mod mfu;
#[cfg(feature = "policy-mru")]
pub mod mru;
#[cfg(feature = "policy-nru")]
pub mod nru;
#[cfg(feature = "policy-random")]
pub mod random;
#[cfg(feature = "policy-s3-fifo")]
pub mod s3_fifo;
#[cfg(feature = "policy-slru")]
pub mod slru;
#[cfg(feature = "policy-two-q")]
pub mod two_q;
